version: '3'
services:
  mycontainer:
    build:
      context: ./first
      dockerfile: Dockerfile
    image: nitesh99sharma/simple-hello:1.0

    networks:
       - mynet
    ports:
      - 80:5000
    volumes:
      - myvol:/data


volumes:
   myvol:

networks:
   mynet:
